sudo: required
services: 
  - docker

before_install:
  - docker build -t udemy_frontend_dev -f Dockerfile.dev .


script:
  # Run test; program should return 'code 0' to indicate success 
  - docker run udemy_frontend_dev npm run test -- --coverage