language: generic 
os: linux
dist: xenial
sudo: required
services: 
  - docker

before_install:
  - docker build -t gagan144/udemy-docker-react -f Dockerfile.dev .

script:
  # - docker run -e CI=true gagan144/udemy-docker-react npm run test -- --coverage
  - docker run -e CI=true gagan144/udemy-docker-react npm run test