language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t udemy_frontend_dev -f Dockerfile.dev .

script:
  # - docker run -e CI=true udemy_frontend_dev npm run test -- --coverage
  - docker run -e CI=true udemy_frontend_dev npm run test