version: '3'
services:
    web:  
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - '3000:3000'
        volumes: 
            - /app/node_modules     # Do not override this volume
            - .:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true  # For windows; reload react app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules     # Do not override this volume
            - .:/app
        command: ["npm", "run", "test"]
        
        